import Head from 'next/head'
import { useEffect, useState, useRef, useLayoutEffect } from 'react'
import { fetchData } from '../libs/FethData';
import { Codes } from '../libs/CodeFlags';
import { Footer } from "@/components/Footer";
import { Historica } from "@/components/Historica";
import { Welcome } from "@/components/Welcome";

export default function Home() {
  const [historica, setHistorica] = useState();

  useEffect(() => {
    const AirtableData = async () => {

      const dataResponse = await fetchData('https://api.airtable.com/v0/app6QkHya20rCFqu4/tbl6L53IbxznTdJxS?filterByFormula=id=21', {
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.NEXT_PUBLIC_AIRTABLE_TOKEN}`
        }
      });

      const Today = dataResponse.records[0];
      let flag = Codes.filter((item) => item.name === Today.fields.country)[0].code
      Today.fields.country = flag;
      setHistorica(Today);
      console.log(Today);
    }
    AirtableData();

  }, []);

  return (
    <>
      <Head>
        <title>Históricas {historica && `| ${historica.fields.fullname}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <Welcome /> */}
      {historica ? <Historica data={historica.fields}/> :<p>Cargando...</p>}
      <Footer />
    </>
  );
};

