import Head from 'next/head'
import { useEffect, useState } from 'react'
import { fetchData } from '../libs/FethData';
import { Codes } from '../libs/CodeFlags';
import { Footer } from "@/components/Footer";
import { Historica } from "@/components/Historica";
import { Welcome } from "@/components/Welcome";
import { GetHistorica, SeenHistorica } from '../libs/GetHistoricaData';
import { generateRandomNumber } from '@/libs/RandomNumber';

import { Firebase } from '../libs/Firebase';

export default function Home() {
  const [historica, setHistorica] = useState();

  useEffect(() => {

    Firebase();

    const AirtableData = async () => {
      const validateToday = await fetchData(`https://api.airtable.com/v0/app6QkHya20rCFqu4/tblVznChX1OvuPF89`, {
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${process.env.NEXT_PUBLIC_AIRTABLE_TOKEN}`
        }
      });

      let dateToday = validateToday.records.filter((item) => item.fields.Date === new Date().toJSON().slice(0,10));

      if (dateToday.length == 0) {

            let oldRadom = validateToday.records.map((item) => item.fields.IdHistorica )
            let IdRandom = generateRandomNumber(1, 21);
            while (oldRadom.includes(IdRandom)) {
              IdRandom = generateRandomNumber(1, 21);
            }

            const result = await fetchData("https://api.airtable.com/v0/app6QkHya20rCFqu4/tblVznChX1OvuPF89", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${process.env.NEXT_PUBLIC_AIRTABLE_TOKEN}`
            },
            body: JSON.stringify({
                "records": [
                    {
                        "fields": {
                            IdHistorica: IdRandom,
                            Date: new Date().toJSON().slice(0,10)
                        }
                    }
                ]
            })
        })

        GetHistorica(result.records[0].fields.IdHistorica, setHistorica);

      } else {
        GetHistorica(validateToday.records[0].fields.IdHistorica, setHistorica);
      }

    }
    AirtableData();

  }, []);

  return (
    <>
      <Head>
        <title>Históricas {historica && `| ${historica.fields.fullname}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {/* <Welcome /> */}
      {historica ? <Historica data={historica.fields}/> :<p>Cargando...</p>}
      <Footer />
    </>
  );
};

